create table if not exists public.plans (
  id bigint generated by default as identity primary key,
  plan_date date not null,
  end_date date not null,
  title text not null,
  place text not null default '',
  memo text not null default '',
  person text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.wishlist (
  id bigint generated by default as identity primary key,
  title text not null,
  category text not null default '',
  person text not null,
  completed boolean not null default false,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

alter table public.wishlist add column if not exists sort_order integer not null default 0;
update public.wishlist
set sort_order = id
where sort_order = 0;

create table if not exists public.memories (
  id bigint generated by default as identity primary key,
  memory_date date not null,
  title text not null,
  place text not null default '',
  memo text not null default '',
  image_path text,
  created_at timestamptz not null default now()
);

alter table public.plans enable row level security;
alter table public.wishlist enable row level security;
alter table public.memories enable row level security;

create policy "app can manage plans" on public.plans for all using (true) with check (true);
create policy "app can manage wishlist" on public.wishlist for all using (true) with check (true);
create policy "app can manage memories" on public.memories for all using (true) with check (true);

insert into storage.buckets (id, name, public)
values ('memory-photos', 'memory-photos', false)
on conflict (id) do nothing;

create policy "app can manage memory photos"
on storage.objects for all
using (bucket_id = 'memory-photos')
with check (bucket_id = 'memory-photos');
